apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy.cloud.kuly/app: ingress
  name: ingress
  namespace: kuly-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy.cloud.kuly/app: ingress
  template:
    metadata:
      labels:
        deploy.cloud.kuly/app: ingress
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: ingress
        ports:
        - containerPort: 12270
          name: rpc
        - containerPort: 443
          name: https
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PORT
          value: "12270"
        - name: CONTROL_PLANE_HOST
          value: control-plane
        - name: CONTROL_PLANE_PORT
          value: "12270"
        - name: HTTP_PORTS
          value: "443"
        - name: CERT_FILE
          value: /tls/tls.crt
        - name: KEY_FILE
          value: /tls/tls.key
        volumeMounts:
        - name: tls-data
          mountPath: "/tls"
      volumes:
      - name: tls-data
        secret:
          secretName: ingress-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    deploy.cloud.kuly/app: ingress
  name: ingress-https
  namespace: kuly-platform
spec:
  type: NodePort
  ports:
    - name: http
      port: 443
      nodePort: 443
      protocol: TCP
      targetPort: https
  selector:
    deploy.cloud.kuly/app: ingress
